[metadata]
package = "github.com/portapps/teamspeak-client-portable"
homepage = "https://github.com/portapps/teamspeak-client-portable"
license = "MIT"

[[constraint]]
  branch = "master"
  name = "github.com/portapps/portapps"
